version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
clone_depth: 1
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    cd source\BookmarkSync.Tests

    dotnet test
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true