version: 1.0.0-{branch}.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: >-
    .\source\BookmarkSync.WebHost\Build-Package.ps1
test_script:
- ps: >-
    Push-Location Source\BookmarkSync.Tests

    try {
      dotnet test
    }
    finally {
      Pop-Location
    }
    
artifacts:
- path: source\BookmarkSync.WebHost\_Published
  name: WebHost
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true